version: "2"
services:
  libremesh_buildroot:
    image: "libremesh/openwrt-buildroot:${TARGET}-${SUBTARGET}-v${OPENWRT_VERSION}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OPENWRT_VERSION=${OPENWRT_VERSION}
        - ARCH_TARGET=${ARCH_TARGET}
        - ARCH_SUBTARGET=${ARCH_SUBTARGET}
        - TARGET=${TARGET}
        - SUBTARGET=${SUBTARGET}
