#!/bin/bash

cat << EOF > .config
CONFIG_DEVEL=y
CONFIG_EXTERNAL_TOOLS=y
CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y
CONFIG_TARGET_ROOTFS_INITRAMFS=y
CONFIG_TARGET_${TARGET}=y
CONFIG_TARGET_${TARGET}_${SUBTARGET}=y
CONFIG_TARGET_MULTI_PROFILE=y
CONFIG_TARGET_PER_DEVICE_ROOTFS=y
CONFIG_IMAGEOPT=y
CONFIG_VERSIONOPT=y
EOF

make defconfig \

cat << EOF >> .config
CONFIG_KERNEL_BUILD_DOMAIN="buildhost"
CONFIG_VERSION_DIST="LibreMesh"
CONFIG_VERSION_NUMBER=\"$(cd feeds/libremesh && git rev-parse --short=7 HEAD)-${OPENWRT_VERSION}\" \
# CONFIG_VERSION_CODE_FILENAMES is not set
# CONFIG_FEED_libremesh is not set
# CONFIG_FEED_profiles is not set
# CONFIG_PACKAGE_dnsmasq is not set
# CONFIG_PACKAGE_odhcpd-ipv6only is not set
# CONFIG_PACKAGE_ppp is not set
# CONFIG_PACKAGE_ppp-mod-pppoe is not set
CONFIG_PACKAGE_kmod-ppp=m
CONFIG_PACKAGE_kmod-pppoe=m
CONFIG_PACKAGE_kmod-pppox=m
EOF

make defconfig
