---
- name: Build docker images
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../targets_22.03.5.yml
  vars:
    dockerfile: ./Dockerfile
    docker_extra_image_name: 
  tasks:
    - name: build
      include_tasks: build_single_target.yml
      loop: "{{ openwrt.archs }}"
      loop_control:
        loop_var: arch

